routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Addresses\Http\Controllers\BpanelAddressController;
use Bittacora\Bpanel4\Addresses\Http\Controllers\PublicAddressController;

Route::prefix('direcciones')->name('bpanel4-addresses.public.')->middleware(['web'])->group(function () {
    Route::post('/crear', [PublicAddressController::class, 'create'])->name('create');
    Route::post('/{address}/actualizar', [PublicAddressController::class, 'update'])->name('update');
    Route::delete('/{address}/elimniar', [PublicAddressController::class, 'destroy'])->name('destroy');
});

Route::prefix('bpanel/direcciones')->name('bpanel4-addresses.bpanel.')->middleware(['web'])->group(function () {
    Route::post('/{address}/actualizar', [BpanelAddressController::class, 'update'])->name('update');
    Route::delete('/{address}/elimniar', [PublicAddressController::class, 'destroy'])->name('destroy');
});

resources/views/bpanel/edit-address-fields.blade.php
{{-- Vista de edición de dirección en bPanel --}}
@livewire('form::input-text', ['name' => 'address[name]', 'labelText' => __('bpanel4-addresses::address.name'), 'required'=>true, 'value' => old('name') ?? $model->name, 'placeholder' => __('bpanel4-addresses::address.name-placeholder')])
<div class="form-group form-row">
    <div class="col-sm-3 col-form-label text-sm-right">
        <label for="id-form-field-1" class="mb-0  ">
            <span class="text-danger">*</span> {{ __('bpanel4-addresses::address.country') }}
        </label>
    </div>
    <div class="col-sm-7">
        @livewire('country-select', ['selectedCountry' => old('selectedCountry') ?? $model->country_id, 'class' => 'form-control'])
    </div>
</div>
<div class="form-group form-row">
    <div class="col-sm-3 col-form-label text-sm-right">
        <label for="id-form-field-1" class="mb-0  ">
            <span class="text-danger">*</span> {{ __('bpanel4-addresses::address.state') }}
        </label>
    </div>
    <div class="col-sm-7">
        @livewire('state-select', ['selectedCountry' => old('selectedCountry') ?? $model->country_id, 'selectedState' => old('selectedState') ?? $model->state_id, 'class' => 'form-control'])
    </div>
</div>
@livewire('form::input-text', ['name' => 'address[location]', 'labelText' => __('bpanel4-addresses::address.location'), 'required'=>true, 'value' => old('location') ?? $model->location])
@livewire('form::input-text', ['name' => 'address[address]', 'labelText' => __('bpanel4-addresses::address.address'), 'required'=>true, 'value' => old('address.address') ?? $model->address])
@livewire('form::input-text', ['name' => 'address[postal_code]', 'labelText' => __('bpanel4-addresses::address.postal-code'), 'required'=>true, 'value' => old('postal_code') ?? $model->postal_code])

resources/views/bpanel/edit-address-form.blade.php
<form class="mt-3 mb-0" method="POST" action="{{ route('bpanel4-addresses.bpanel.update', ['address' => $address]) }}">
    @include('bpanel4-addresses::bpanel.edit-address-fields', ['model' => $address])
    @csrf
    <input type="hidden" name="_address-token" value="{{ \Illuminate\Support\Facades\Crypt::encryptString($address->id) }}">
    <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
        @livewire('form::save-button',['theme'=>'update'])
        @livewire('form::save-button',['theme'=>'reset'])
    </div>
</form>

resources/views/bpanel/livewire/addresses-datatable.blade.php
<td>
    {{ $row->name }}
</td>
<td>
    {{ $row->country->name }}
</td>
<td>
    {{ $row->state->name }}
</td>
<td>
    {{ $row->location }}
</td>
<td>
    {{ $row->postal_code }}
</td>
<td>
    @livewire('utils::datatable-poly-default', [
        'fieldName' => 'main',
        'model' => $row,
        'value' => $row->main,
        'size' => 'xxs',
        'relationName' => 'addressable',
        'reloadRouteName' => Illuminate\Support\Facades\Route::currentRouteName(),
        'reloadRouteParams' => (Illuminate\Support\Facades\Route::getCurrentRoute())->originalParameters()
    ], key('main-address-'.$row->id))
</td>
<td>
    <a href="{{ route($editAddressRouteName, ['address' => $row->id]) }}" class="edit-address-button"><i class="fa fa-pencil"></i></a>
    <form method="POST" class="d-inline mx-2"
          action="{{route('bpanel4-addresses.public.destroy', ['address' => $row->id])}}">
        {!!method_field('DELETE')!!}
        @csrf
        <button id="delete_button{{$model->id}}" type="submit" class="btn btn-primary-outline text-danger"
                onclick="return confirm('¿Está seguro de querer borrar esta dirección?')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</td>

@pushonce('scripts')
<script>
    document.querySelector('a[wire\\:click\\.prevent="bulkDelete"]').addEventListener('click', function(event) {
      if (!window.confirm('¿Seguro que desea eliminar los elementos seleccionados?')) {
        event.preventDefault();
        event.stopPropagation();
        return false;
      }
    }, true);
</script>
@endpushonce